//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiento
    {
        public int numeroAsiento { get; set; }
        public string tipo { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<bool> seleccionado { get; set; }
        public Nullable<int> idCompraAsi { get; set; }
        public int aeronaveNum { get; set; }
        public string fila { get; set; }
        public int desde { get; set; }
        public int hasta { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Aeronave Aeronave { get; set; }
    }
}
