//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intercontinental
    {
        public string numeroVuelo { get; set; }
        public string origen { get; set; }
        public string destino { get; set; }
        public System.DateTime dtLlegada { get; set; }
        public System.DateTime dtSalida { get; set; }
        public double HorasTotales { get; set; }
        public Nullable<int> numeroAeronaveAsignada { get; set; }
        public double precio { get; set; }
        public string documentacion { get; set; }
        public double tasaInter { get; set; }
        public string visa { get; set; }
        public int NumAeroI { get; set; }
    
        public virtual Aeronave Aeronave { get; set; }
    }
}
