//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nacional
    {
        public string numVuelo { get; set; }
        public string departamento { get; set; }
        public int idNacional { get; set; }
    
        public virtual Vuelo Vuelo { get; set; }
    }
}
