//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int idPago { get; set; }
        public string tipoPago { get; set; }
        public int numeroTarjeta { get; set; }
        public System.DateTime dtVencimiento { get; set; }
        public int idCompraFk { get; set; }
    
        public virtual Compra Compra { get; set; }
    }
}
