//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public string UrlAeronave { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<double> visitas { get; set; }
        public int numAeronave { get; set; }
    
        public virtual Aeronave Aeronave { get; set; }
    }
}
